return {
  save_location = vim.fn.stdpath('data') .. '/',
  save_file = 'kanban.json',
  main = {
    title = 'Choose board',
  },
  input = {
    width = 20,
    height = 20,
  },
  keymap = {
    select = '<CR>',
    remove_item = 'x',
    remove_column = 'X',
    swap_column_left = '<c-h>',
    swap_column_right = '<c-l>',
    create_left = 'i',
    create_right = 'a',
    create_left_first = 'I',
    create_right_last = 'A',
    create_below = 'o',
    create_above = 'O',
    go_left = 'h',
    go_right = 'l',
    move_item_up = 'K',
    move_item_down = 'J',
    move_item_left = 'H',
    move_item_right = 'L',
    edit_column = 'e',
  },
}
